const PASSWORD_SALT = "$2b$10$F4fR7HZzGOTRBLwwMVl9Xe";
const ACCESS_TOKEN_SECRET = "$2b$10$F4fR7HZzGOTRBLwwMVl9Xe";
const REFRESH_TOKEN_SECRET = "$2b$10$F4fR7HZzGOTRBLwwMVl9Xe";
const ACCESS_TOKEN_EXPIRES_IN = "1m";
const REFRESH_TOKEN_EXPIRES_IN = "5m";

export {
  PASSWORD_SALT,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN,
};
